//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public int fid { get; set; }
        public string FileName { get; set; }
        public string Sdsfid { get; set; }
    }
}
