//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id { get; set; }
        public string Product1 { get; set; }
        public string CommonName { get; set; }
        public string Manufacturer { get; set; }
        public string ManufacturerNo { get; set; }
        public string MaterialNumber { get; set; }
        public Nullable<System.DateTime> DateRevision { get; set; }
        public Nullable<System.DateTime> DateReviewed { get; set; }
        public string Health { get; set; }
        public string Flammibility { get; set; }
        public string Reactive { get; set; }
        public string Protection { get; set; }
        public string WebSite { get; set; }
        public string Locations { get; set; }
        public string CompaniesRelated { get; set; }
        public string Comments { get; set; }
        public string Sdsid { get; set; }
    }
}
